version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./dist:/usr/src/app/static/dist
      - ./testrpc-data:/usr/src/app/.testrpc
      - ./contracts:/usr/src/app/node_modules/signhash-contracts/build
      - ./output:/usr/src/app/output
    environment:
      - RPC_URL=http://app:8545
    expose:
      - "8080"
      - "8545"
    command: npm-run-all -p testrpc:persist:run start:prod:serve
    cached: true
  e2e:
    build:
      context: ./tests/e2e/
      dockerfile: docker/testcafe/Dockerfile
    links:
      - "app"
    volumes:
      - ./tests/e2e:/work
      - ./tests/data:/data
    environment:
      - SIGNHASH_URL=http://app:8080
    cached: true
